language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
env:
  - DJANGO_VERSION=1.6.10
  - DJANGO_VERSION=1.7.6
install: 
- pip install Django==$DJANGO_VERSION pytest
- python setup.py install
script: py.test
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.7.6
